<?php

/**
 * Implements hook_init().
 */
function find_init(){

    set_include_path(get_include_path() . PATH_SEPARATOR . __DIR__);
    set_include_path(get_include_path() . PATH_SEPARATOR . __DIR__ . '/elastica/lib');

    spl_autoload_register('find_autoload');
}

/**
 * Autoloader for Naturwerk\Find and Elastica_.
 */
function find_autoload($class) {

    if (substr($class, 0, 14) == 'Naturwerk\\Find') {

        $file = str_replace('\\', '/', $class) . '.php';

        require_once $file;

    } else if (substr($class, 0, 9) == 'Elastica_') {

        $file = str_replace('_', '/', $class) . '.php';

        require_once $file;
    }
}

/**
 * Implements hook_menu()
 *
 * @return array
 */
function find_menu() {

    $items = array();

    $items['find'] = array(
        'title' => t('Search'),
        'description' => t('Search Natuwerk'),
        'page callback' => 'find_show_search',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'find.views.inc.php',
    );

    $items['find/organisms'] = array(
        'title' => t('Tiere und Pflanzen'),
        'description' => t('Search Natuwerk'),
        'page callback' => 'find_show_search_organisms',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'find.views.inc.php',
    );

    $items['find/sightings'] = array(
        'title' => t('Beobachtungen'),
        'description' => t('Search Natuwerk'),
        'page callback' => 'find_show_search_sightings',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'find.views.inc.php',
        'weight' => 10,
    );

    $items['find/inventories'] = array(
        'title' => t('Inventare'),
        'description' => t('Search Natuwerk'),
        'page callback' => 'find_show_search_inventories',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'find.views.inc.php',
        'weight' => 20,
    );

    return $items;
}


/**
 * Implements hook_theme()
 *
 * @return an array with theme template information
 */
function find_theme() {
    return array(
        'find.search' => array(
            'template' => 'find.search',
            'variables' => array('result' => null, 'sort' => array(), 'search' => '', 'class' => null, 'user' => null, 'family' => null, 'genus' => null, 'geo' => array(), 'date' => array(), 'box' => array(), 'organisms' => null, 'sightings' => null, 'inventories' => null)
    ),
        'find_facet' => array(
            'template' => 'find_facet',
            'variables' => array('facets' => array(), 'filters' => array(), 'title' => null, 'field' => null, 'value' => null)
    ),
    );
}

/**
 * Implements hook_cron()
 */
function find_cron() {

    $client = new Elastica_Client();
    $index = $client->getIndex('naturwerk');

    $indexer = new Naturwerk\Find\Indexer($index);
    $indexer->all();
}
