<?php

define('AREA_ACCESS', 'area access');
define('AREA_CREATE', 'area create');

/**********************************
 *  Hook implementations
 *********************************/

/**
 * Implements hook_help()
 *
 * @param $path
 * @param $arg
 * @return string
 */
function area_help($path, $arg) {
	switch ($path) {
		case "admin/help#area":
			return '<p>'.  t("Area module") .'</p>';
			break;
	}
}

/**
 * Implements hook_menu()
 *
 * @return array
 */
function area_menu() {
	$items['area'] = array(
    'title' => 'Search area',
    'description' => 'Find areas',
    'page callback' => 'show_area_search',
    'access arguments' => array(AREA_ACCESS),
	'file' => 'area.search.inc',
	);
	$items['area/search'] = array(
    'title' => 'Search',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
	);
	$items['area/new_map'] = array(
    'title' => 'New area',
    'description' => 'Create an area',
    'page callback' => 'show_area_new_map',
	'access arguments' => array(AREA_CREATE),
    'type' => MENU_LOCAL_TASK,
	'weight' => 5,
	'file' => 'area.new.map.inc',
	);
	$items['area/new_prop'] = array(
	'title' => 'New area',
	'description' => 'Create an area',
	'page callback' => 'show_area_new_prop',
	'access arguments' => array(AREA_CREATE),
	'type' => MENU_CALLBACK,
	'file' => 'area.new.prop.inc',
	);
	$items['area/%'] = array(
    'title' => 'Area',
    'description' => 'View area',
    'page callback' => 'show_area',
	'page arguments' => array(1),
    'access arguments' => array(AREA_ACCESS),
    'type' => MENU_CALLBACK,
	'file' => 'area.inc',
	);

	return $items;
}

/**
 * Implements hook_theme()
 *
 * @return an array with theme template information
 */
function area_theme() {
	return array(
    	'area.search' => array(
 			'template' => 'area.search',
    	  	'variables' => array()
	),
		'area.new.map' => array(
			'template' => 'area.new.map',
			'variables' => array()
	)
	);
}

function area_permission() {
  return array(
    AREA_ACCESS =>  array(
      'title' => t('can view areas'),
    ),
    AREA_CREATE =>  array(
      'title' => t('can create areas'),
    ),
  );
}
?>