<?php
/**********************************
 *  Hook implementations
 *********************************/

//module_load_include('inc', 'habitat');

/**
 * Implements hook_menu()
 *
 * @return array
 */
function habitat_menu() {
	$items['habitat'] = array(
    'title' => 'List Habitat',
    'description' => 'Show all habitats',
    'page callback' => 'habitat_list',
    'access arguments' => array('access habitats'),
	'file' => 'habitat.list.inc',
	);
	$items['habitat/%'] = array(
    'title' => 'Show Habitat Areas',
    'description' => 'View existing Habitat Areas',
    'page callback' => 'habitat_show',
	'access arguments' => array('access content'),
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
	'file' => 'habitat.show.inc',
	);
  	return $items;
}


?>