<?php
/**********************************
 *  Hook implementations
 *********************************/

//module_load_include('inc', 'habitat');

/**
 * Implements hook_menu()
 *
 * @return array
 */
function habitat_menu() {
  $items['habitat'] = array(
    'title' => t('Habitats'),
    'description' => t('Show all habitats'),
    'page callback' => 'habitat_list',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'habitat.list.inc',
  );
  $items['habitat/%'] = array(
    'title' => 'Show Habitat Areas',
    'description' => 'View existing Habitat Areas',
    'page callback' => 'habitat_show',
    'access arguments' => array('access content'),
    'page arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'habitat.show.inc',
  );
  return $items;
}

/**
 * Implements hook of gallery module to activate the gallery
 * functionality for habitat
 * 
 * @return array
 */
function habitat_gallery_types() {
  return array(
    'habitat' => array(
      'image_caption' => 'habitat_gallery_image_caption'
    )
  );
}

/**
 * Helper function referenced in habitat_gallery_types to define the caption
 * for images added to intentory entries
 * 
 * @return string
 */
function habitat_gallery_image_caption($id) {
  $result = db_select('habitat', 'h')
    ->condition('id', $id)
    ->fields('h')
    ->execute()
    ->fetch();
  return l($result->label.' '.$result->name_de.' <small>'.$result->name_lt.'</small>', 'habitat/'.$id, array('html' => true));
}

/**
 * Implements hook of gallery module to define the different category
 * conditions available for habitat types
 * 
 * @return array
 */
function habitat_gallery_category_conditions() {
  return array(
    'habitat' => array(
      'name' => t('Habitats'),
      'type' => 'habitat'
    ),
  );
}


?>