<?php
/**********************************
 *  Hook implementations
 *********************************/

/**
 * Implements hook_menu()
 *
 * @return array
 */
function naturvielfalt_webservice_menu() {
	$items['webservice/api'] = array(
			'title' => t('Webservice'),
			'page callback' => 'naturvielfalt_webservice_parse_import_observations',
			'access arguments' => array(
					'access webservice'
			),
			'file' => 'naturvielfalt_webservice.inc',
	);
	return $items;
}

/**
 * Default permission function
 *
 */
function naturvielfalt_webservice_permission() {
	return array(
			'access webservice' => array(
					'title' => t('can access the webservice'),
			),
	);
}

?>
