<?php
/**********************************
 *  Hook implementations
 *********************************/

/**
 * Implements hook_menu()
 *
 * @return array
 */
function webservice_menu() {
	$items['webservice/api/observation'] = array(
			'title' => t('Webservice'),
			'page callback' => 'webservice_parse_import_observations',
			'access arguments' => array(
					'access webservice'
			),
			'file' => 'webservice_observation.inc',
	);
	
	$items['webservice/api/area'] = array(
			'title' => t('Webservice'),
			'page callback' => 'webservice_parse_import_areas',
			'access arguments' => array(
					'access webservice'
			),
			'file' => 'webservice_area.inc',
	);
	
	$items['webservice/api/inventory'] = array(
			'title' => t('Webservice'),
			'page callback' => 'webservice_parse_import_inventories',
			'access arguments' => array(
					'access webservice'
			),
			'file' => 'webservice_inventory.inc',
	);
	
	$items['webservice/api'] = array(
			'title' => t('Webservice'),
			'page callback' => 'webservice_parse_import_observations_lightversion',
			'access arguments' => array(
					'access webservice'
			),
			'file' => 'webservice_observation.inc',
	);
	return $items;
}

/**
 * Default permission function
 */
function  webservice_permission() {
	return array(
			'access webservice' => array(
					'title' => t('can access the webservice'),
			),
	);
}

?>
