<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de">

<head>
<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/main.css');
$this->headScript()->appendFile($this->baseUrl() . '/js/util.js');
		
echo $this->headTitle();
echo $this->headMeta();
echo $this->headStyle();
echo $this->headLink();
echo $this->headScript();
?>
</head>

<body>
<div id="header">
<div id="headerBar">
<p>Swissmon Alpha</p>
</div>
<div id="topnav"><?php echo $this->navigation()->menu()->renderMenu(null, array('minDepth' => 1, 'maxDepth' => 1)) ?>
</div>
<div id="subnav"><?php echo $this->navigation()->menu()->renderMenu(null, array('minDepth' => 2, 'maxDepth' => 2, 'onlyActiveBranch' => true)) ?></div>

</div>
<div id="content"><?php echo $this->layout()->content ?></div>

</body>
</html>
