<?php

/**********************************
 *  Hook implementations
 *********************************/

/**
 * Implements hook_help()
 *
 * @param $path
 * @param $arg
 * @return string
 */
function inventory_help($path, $arg) {
	switch ($path) {
		case "admin/help#inventory":
			return '<p>'.  t("Inventory module") .'</p>';
			break;
	}
}

/**
 * Implements hook_block_info()
 *
 * Provides information about available blocks.
 *
 * @return array
 */
function inventory_block_info() {
	$blocks['inventory'] = array( // The unique name of the block.
    'info' => t('Swissmon Inventory'), // The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, // Default
	);
	return $blocks;
}

/**
 * Implements hook_block_view()
 *
 * Callback for to displaying a block.
 *
 * @param  $delta which block to display. see showcase_block_info()
 * @return String
 */
function inventory_block_view($delta = '') {
	$item = array('data' => l("Link to inventory page", 'inventory'));
	$block['content'] = theme('inventory_item', array('item' => $item));
	return $block;
}

/**
 * Implements hook_theme()
 *
 * publishes our template
 * @return an array with theme template information
 */
function inventory_theme() {
	return array(
    'inventory_item' => array(
      'template' => 'inventory_item',
      'variables' => array('item' => NULL)
	)
	);
}


/**
 * Implements hook_menu()
 *
 * This makes it possible to visit the link drupal/?q=showcase.
 * It is also possible to create an URL like drupal/?q=showcase/42. This would show probably the element with the ID 42.
 *
 * @return array
 */
function inventory_menu() {
	$items['inventory/%'] = array(
    'title' => 'Inventory Url',
    'description' => 'Swissmon Inventory',
    'page callback' => 'inventory_page',
	'page arguments' => array(1),
    'access arguments' => array('access inventory'),
    'type' => MENU_SUGGESTED_ITEM,
	'file' => 'inventory.pages.inc',
	);
	return $items;
}

?>
