<?php
/**********************************
 *  Hook implementations
 *********************************/

/**
 * Implements hook_menu()
 *
 * @return array
 */
//FIXME document this...
function sgroup_menu() {
	$items['user/%user/sgroup'] = array(
			'title' => 'Groups',
			'description' => 'Shows ones groups',
			'page callback' => 'sgroup_overview',
			'access arguments' => array(
					'access sgroup'
			),
			'type' => MENU_LOCAL_TASK,
			'file' => 'sgroup.overview.inc'
	);
	$items['user/%user/sgroup/show'] = array(
			'title' => 'Show groups',
			'type' => MENU_DEFAULT_LOCAL_TASK,
			'weight' => -10,
	);
	$items['user/%user/sgroup/new'] = array(
			'title' => 'Create a new group',
			'description' => 'Create a new group',
			'page callback' => 'sgroup_new',
			'access arguments' => array(
					'access sgroup'
			),
			'type' => MENU_LOCAL_TASK,
			'weight' => 5,
			'file' => 'sgroup.new.inc',
	);
	$items['user/%user/sgroup/%/edit'] = array(
			'title' => 'Edit group',
			'description' => 'Edit group',
			'page callback' => 'sgroup_edit',
			'page arguments' => array(
					3
			),
			'access callback' => 'sgroup_edit_access',
			'access arguments' => array(
					3
			),
			'type' => MENU_NORMAL_ITEM,
			'file' => 'sgroup.edit.inc',
	);
	$items['sgroup/delete_member/%/%'] = array(
			'title' => 'JSON request to delete a member from a group',
			'page callback' => 'sgroup_delete_member',
			'page arguments' => array(
					2,
					3
			),
			'access callback' => 'sgroup_edit_access',
			'access arguments' => array(
					2
			),
			'type' => MENU_CALLBACK,
			'file' => 'sgroup.edit.inc',
	);
	return $items;
}

function sgroup_permission() {
	return array(
			'access sgroup' => array(
					'title' => t('can view, create and manage swissmon groups')
			)
	);
}

//FIXME document this...
function sgroup_edit_access($sgroupId) {
	$access = user_access('access sgroup');
	// check if this user is administrator of the group
	global $user;
	$adminRecords = db_query('SELECT 
				admin
			FROM 
				sgroup_users
			WHERE 
				sgid=:sgid AND
				uid=:uid', array(':sgid' => $sgroupId,
					':uid' => $user->uid
			));
	$admin = $adminRecords->fetch();
	$access = $access && $admin->admin == 1;
	return $access;
}

?>