<!-- application/views/scripts/area-select/index.phtml -->
  <h2>Gebiet auswählen</h2>
  <?php echo $this->debug ?>
  <div>
    <table cellpadding="0" cellspacing="0" border="0" class="display" id="area_table">
   
   </table>
  </div>
 <br/>
  <div>
    <dd id="map_search-element">
      <input type="text" id= "map_search" name="map_search" value="" />
      <button id="map_search_button">Los</button>
   </dd>  
  </div>
  <div id='map'>
     <div id="map_canvas">  </div>
  </div>
 <div>
     <button id="new-area">Neues Gebiet</button>
     <button id="create-inventory">Inventar erstellen</button>
 </div>


  


