<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color:#008000;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-color: #333333;
        width:  100%;
        height: 100%;
        border: 2px solid #FFFFFF;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>Welcome to <span id="zf-name">Swissmon Alpha!</span></h1>

    <h3>This is your main page</h3>

</div>