<?php

/**********************************
 *  Hook implementations
 *********************************/

// Load gallery integration
module_load_include('inc', 'organism', 'organism.gallery');

/**
 * Implements hook_theme()
 *
 * publishes our template
 * @return an array with theme template information
 */
function organism_theme() {
  return array(
    'showcase_block' => array(
     'template' => 'organism_page',
     'variables' => array('item' => NULL)
    )
  );
}


/**
 * Implements hook_menu()
 *
 * This makes it possible to visit the link drupal/organism.
 * It is also possible to create an URL like drupal/organism/42. This would show probably the element with the ID 42.
 *
 * @return array
 */
function organism_menu() {
  
  $items['organism'] = array(
    'title' => t('Organisms'),
    'page callback' => 'organism_overview',
    'access arguments' => array('access content'),
    'description' => t('List of organisms'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'organism.overview.inc',
  );
  $items['organism/%'] = array(
    'title' => 'Basisinfo',
    'description' => 'Show organism',
    'page callback' => 'organism_show',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'organism.show.inc',
  );
  $items['organism/%/normal'] = array(
    'title' => 'Basisinfo',
    'description' => 'Show organism',
    'page callback' => 'organism_show',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK | MENU_NORMAL_ITEM,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'organism.show.inc',
  );  
  $items['organism/type/%'] = array(
    'title' => 'Lexikon',
    'description' => 'Show organism',
    'page callback' => 'organism_showtype',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'organism.showtype.inc',
  );
  $items['organism/%/lexikon'] = array(
    'title' => t('Lexikon'),
    'description' => 'Show organism lexika',
    'page callback' => 'organism_lexika_show',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK | MENU_NORMAL_ITEM,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'organism.lexika.inc',
  );
  
  return $items;
}

?>
