<?php

/**********************************
 *  Hook implementations
 *********************************/




/**
 * Implements hook_theme()
 *
 * publishes our template
 * @return an array with theme template information
 */
function organism_theme() {
	return array(
    'showcase_block' => array(
 		'template' => 'organism_page',
      	'variables' => array('item' => NULL)
	)
	);
}


/**
 * Implements hook_menu()
 *
 * This makes it possible to visit the link drupal/organism.
 * It is also possible to create an URL like drupal/organism/42. This would show probably the element with the ID 42.
 *
 * @return array
 */
function organism_menu() {
	
	$items['organism'] = array(
	'title' => t('Organism'),
    'page callback' => 'organism_overview',
    'access arguments' => array('access content'),
    'description' => t('Shows organisms from DB'),
    'type' => MENU_NORMAL_ITEM,
	'file' => 'organism.overview.inc',
	);
	/*$items['organism'] = array(
    'title' => 'Organism',
    'description' => 'Shows a page with our own template organism_page.tpl.php.',
    'page callback' => 'organism_page',
    'access arguments' => array('access organism'),
    'type' => MENU_NORMAL_ITEM,
	//'file' => 'organism.pages.inc',
	);*/

	$items['organism/%'] = array(
    'title' => 'Area',
    'description' => 'Show organism',
    'page callback' => 'organism_show',
	'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
	'file' => 'organism.show.inc',
	);
	
	$items['organism/type/%'] = array(
    'title' => 'Area',
    'description' => 'Show organism',
    'page callback' => 'organism_showtype',
	'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
	'file' => 'organism.showtype.inc',
	);
	
	return $items;
}

/**
 * Implements hook of gallery module to activate the gallery
 * functionality for organism
 * 
 * @return array
 */
function organism_gallery_types() {
  return array(
    'organism' => array(
      'edit_gallery' => 'organism_gallery_access_callback',
      'image_caption' => 'organism_gallery_image_caption'
    )
  );
}

/**
 * Helper function referenced in organism_gallery_types to define the edit access
 * for images added to organisms
 * 
 * @param string $type
 *   The type of object to be accessed
 * @param string $id
 *   The id of object to be accessed
 * @param array $image
 *   The image to be accessed.
 * @return boolean
 */
function organism_gallery_access_callback($type, $id, $image=false) {
  return false; // restrict access to users having the 'manage gallery images' permission
}

/**
 * Helper function referenced in organism_gallery_types to define the caption
 * for images added to organisms
 * 
 * @param $id
 * @return string
 */
function organism_gallery_image_caption($id) {
  $result = db_query('SELECT '.
                      'o.organism_type, '.
                      'fauna.name_de AS fauna_name, '.
                      'fauna.genus AS fauna_genus, '.
                      'fauna.species AS fauna_species, '.
                      'flora.name_de AS flora_name, '.
                      'flora."Gattung" AS flora_gattung, '.
                      'flora."Art" AS flora_art '.
                     'FROM '.
                      'organism AS o '.
                     'LEFT OUTER JOIN fauna_organism AS fauna ON fauna.id = o.organism_id '.
                     'LEFT OUTER JOIN flora_organism AS flora ON flora.id = o.organism_id '.
                     'WHERE '.
                      'o.id = :id', array(':id' => $id));
  $result = $result->fetch();
  if($result->organism_type == '1')
    return $result->fauna_name.' <small>'.$result->fauna_genus.' '.$result->fauna_species.'</small>';
  return $result->flora_name.' <small>'.$result->flora_gattung.' '.$result->flora_art.'</small>';
}

/**
 * Implements hook of gallery module to define the different category
 * conditions available for organisms
 * 
 * @return array
 */
function organism_gallery_category_conditions() {
  return array(
    'organism' => array(
      'name' => t('Organisms'),
      'type' => 'organism'
    ),
    'organism_flora' => array(
      'name' => t('Flora'),
      'type' => 'organism',
      'table' => 'organism',
      'column' => 'organism_type',
      'value' => '2'
    ),
    'organism_fauna' => array(
      'name' => t('Fauna'),
      'type' => 'organism',
      'table' => 'organism',
      'column' => 'organism_type',
      'value' => '1'
    ),
    'organism_flora_custom' => array(
      'name' => t('Flora individual'),
      'type' => 'organism',
      'table' => array('flora_organism', array(
        'organism_id' => 'flora_organism.id',
        'organism_type' => '2'
      )),
      'columns' => array(/*
        'Familie' => t('Familie'),
        'Gattung' => t('Gattung'),
        'Art' => t('Art'),*/
        'is_neophyte' => t('Neophyte')
      )
    ),
    'organism_fauna_custom' => array(
      'name' => t('Fauna individual'),
      'type' => 'organism',
      'table' => array('fauna_organism', array(
        'organism_id' => 't.id',
        'organism_type' => '1'
      )),
      'columns' => array(
        'fauna_class_id' => array(t('Inventory Group'), 'organism_gallery_catgory_invgroup_columns'),/*
        'family' => t('Family'),
        'genus' => t('Genus'),
        'sub_genus' => t('Sub genus'),
        'species' => t('Species'),
        'sub_species' => t('Sub species')*/
      ),
    ),
  );
}

/**
 * Option factory for the organism_fauna_custom condition
 * 
 * @return array
 */
function organism_gallery_catgory_invgroup_columns() {
  $result = db_select('fauna_class', 'fc', array('fetch' => PDO::FETCH_ASSOC))->fields('fc')->execute()->fetchAll();
  $columns = array();
  foreach($result as $record)
    $columns[$record['id']] = $record['name_de'];
  return $columns;
}

?>
