INSERT INTO {habitat} (id,label,name,notes) VALUES (1,'1','Gewässer',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (2,'1.1','Stehende Gewässer',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (3,'1.1.0','Stehendes Gewässer ohne Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (4,'1.1.0.1','Tiefgründiges Gewässer (Freiwasserzone)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (5,'1.1.0.2','Seichtes Gewässer (Litoral, inkl. Tümpel)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (6,'1.1.1','Armleuchteralgenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (7,'1.1.2','Laichkrautgesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (8,'1.1.3','Wasserlinsengesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (9,'1.1.4','Seerosengesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (10,'1.2','Fliessgewässer',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (11,'1.2.1','Brachsmen- und Barbenregion',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (12,'1.2.1.1','Breites Fliessgewässer des Flachlands',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (13,'1.2.1.2','Langsam fliessender Bach im Flachland',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (14,'1.2.2','Äschenregion (Hyporhithron)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (15,'1.2.2.0','Äschenregion ohne Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (16,'1.2.2.1','Äschenregion mit Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (17,'1.2.3','Untere Forellenregion (Metarhithron)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (18,'1.2.4','Obere Forellenregion (Epirhithron)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (19,'1.2.5','Temporärer Wasserlauf',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (20,'1.3','Quellen und Quellfluren',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (21,'1.3.0','Überrieselte Fläche, Quelle ohne Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (22,'1.3.1','Kalktuff-Felsspaltengesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (23,'1.3.2','Kalk-Quellflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (24,'1.3.3','Weichwasser-Quellflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (25,'1.4','Unterirdische Gewässer',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (26,'1.4.1','Porengrundwasser',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (27,'1.4.2','Kluftgrundwasser',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (28,'1.4.3','Höhlenbach',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (29,'1.4.4','Höhlensee',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (30,'2','Vegetation der Ufer und der Feuchtgebiete',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (31,'2.0','Ufer ohne Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (32,'2.1','Ufer mit Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (33,'2.1.1','Wasserschlauch-Moortümpelgesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (34,'2.1.2','Röhricht',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (35,'2.1.2.1','Stillwasser-Röhricht',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (36,'2.1.2.2','Landschilf-Röhricht',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (37,'2.1.3','Strandlingsgesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (38,'2.1.4','Bach- und Flussröhricht',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (39,'2.2','Flachmoore',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (40,'2.2.1','Grossseggenbestände',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (41,'2.2.1.1','Grossseggenried',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (42,'2.2.1.2','Schneidbinsenried',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (43,'2.2.2','Saures Kleinseggenried',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (44,'2.2.3','Kalk-Kleinseggenried',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (45,'2.2.4','Übergangsmoor',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (46,'2.2.5','Schwemmufervegetation alpiner Wildbäche',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (47,'2.3','Feucht- und Nasswiesen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (48,'2.3.1','Pfeifengraswiese',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (49,'2.3.2','Sumpfdotterblumenwiese',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (50,'2.3.3','Spierstaudenflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (51,'2.4','Hochmoore',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (52,'2.4.1','Torfmoos-Hochmoor',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (53,'2.5','Zeitweilig überflutete Annuellenfluren',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (54,'2.5.1','Zwergbinsen-Annuellenflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (55,'2.5.2','Nitrophile Annuellenvegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (56,'3','Gletscher, Fels, Schutt und Geröll',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (57,'3.1','Gletscher, Firn',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (58,'3.1.1','Gletscher',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (59,'3.1.2','Blockgletscher',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (60,'3.1.3','Firnfeld (Sommer)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (61,'3.1.4','Schneefeld (Frühling)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (62,'3.2','Alluvionen und Moränen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (63,'3.2.1','Alluvionen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (64,'3.2.1.0','Alluvionen ohne Vegtetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (65,'3.2.1.1','Alluvionen mit krautiger Pioniervegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (66,'3.2.2','Moräne',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (67,'3.2.2.0','Moräne ohne Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (68,'3.2.2.1','Moräne mit Pioniervegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (69,'3.3','Steinschutt- und Geröllfluren',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (70,'3.3.1','Kalkschutt',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (71,'3.3.1.1','Kalkschutthalde ohne Gefässpflanzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (72,'3.3.1.2','Alpine Kalkblockflur (hartes Gestein)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (73,'3.3.1.3','Alpine Kalkschieferflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (74,'3.3.1.4','Feuchte Kalkschuttflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (75,'3.3.1.5','Sommerwarme Kalkschuttflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (76,'3.3.2','Silikatschutt',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (77,'3.3.2.1','Silikatschutthalde ohne Gefässpflanzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (78,'3.3.2.2','Alpine Silikatschuttflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (79,'3.3.2.3','Sommerwarme Silikatschuttflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (80,'3.4','Felsen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (81,'3.4.1','Kalkfelsen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (82,'3.4.1.1','Kalkfelsflur ohne Gefässpflanzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (83,'3.4.1.2','Sonnige Kalkfelsflur mit Gefässpflanzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (84,'3.4.1.3','Schattige Kalkfelsflur mit Gefässpflanzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (85,'3.4.2','Silikat-, Serpentinfelsen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (86,'3.4.2.1','Silikatfelsflur ohne Gefässpflanzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (87,'3.4.2.2','Silikatfelsflur mit Gefässpflanzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (88,'3.4.2.3','Serpentingesteinsflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (89,'3.5','Höhlen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (90,'3.5.1','Bereich der Unterseite von Steinen, Blöcken, etc.',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (91,'3.5.2','Tierbau (pholeophile Fauna)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (92,'3.5.3','Höhlenwandgesellschaften (Höhleneingang)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (93,'3.5.4','Guanohaufen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (94,'3.5.5','Künstliche Höhlung (Minen, Tunnel)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (95,'3.5.6','Lehmablagerung im Höhleninneren',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (96,'3.5.7','Fels im Höhleninneren',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (97,'4','Rasen, Wiesen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (98,'4.0','Kunstrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (99,'4.0.1','Kunstwiese auf Fruchtfolgefläche',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (100,'4.0.2','Kunstrasen auf Sportplätzen, im Siedlungsraum, etc.',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (101,'4.0.4','Begrünung in Hochlagen (Skipisten, etc.)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (102,'4.1','Felsgrus- und Karstfluren',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (103,'4.1.1','Thermophile Kalkfelsgrusflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (104,'4.1.2','Kalkfelsgrusflur des Gebirges (Karstgebiet)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (105,'4.1.3','Thermophile Silikatfelsgrusflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (106,'4.1.4','Silikatfesgrusflur des Gebirges',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (107,'4.2','Wärmeliebende Trockenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (108,'4.2.1','Kontinentaler Trockenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (109,'4.2.1.1','Inneralpine Felsensteppe',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (110,'4.2.1.2','Kontinentaler Halbtrockenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (111,'4.2.2','Subatlantischer Trockenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (112,'4.2.3','Insubrischer Trockenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (113,'4.2.4','Subatlantischer Halbtrockenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (114,'4.3','Magerrasen der Hochlagen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (115,'4.3.1','Blaugrashalde',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (116,'4.3.2','Polsterseggenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (117,'4.3.3','Rostseggenhalde',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (118,'4.3.4','Nacktriedrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (119,'4.3.5','Borstgrasweide',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (120,'4.3.6','Buntschwingelrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (121,'4.3.7','Krummseggenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (122,'4.4','Schneetälchen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (123,'4.4.1','Kalk-Schneetälchen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (124,'4.4.2','Sauerboden-Schneetälchen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (125,'4.5','Fettwiesen und -weiden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (126,'4.5.1','Fromentalwiese',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (127,'4.5.2','Goldhaferwiese',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (128,'4.5.3','Kammgrasweide',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (129,'4.5.4','Milchkrautweide',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (130,'4.6','Grasbrachen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (131,'4.6.1','Ruderaler Halbtrockenrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (132,'4.6.2','Fiederzwenckenbrache',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (133,'4.6.3','Fromentalbrache',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (134,'4.6.4','Pfeifengrasbrache',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (135,'4.6.5','Reitgrasbrache',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (136,'5','Krautsäume, Hochstaudenfluren, Gebüsche',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (137,'5.1','Saumgesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (138,'5.1.1','Trockenwarmer Krautsaum',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (139,'5.1.2','Mesophiler Krautsaum',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (140,'5.1.3','Feuchter Krautsaum der Tieflagen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (141,'5.1.4','Feuchter Krautsaum der höheren Lagen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (142,'5.1.5','Nährstoffreicher mesophiler Krautsaum',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (143,'5.2','Hochstaudenfluren, Waldschläge',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (144,'5.2.1','Schlagflur, Waldlichtung auf basenreichem Boden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (145,'5.2.2','Schlagflur, Waldlichtung auf saurem Boden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (146,'5.2.3','Montan-subalpine Hochgrasflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (147,'5.2.4','Subalpine Hochstaudenflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (148,'5.2.5','Adlerfarnflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (149,'5.3','Gebüsche (Waldmäntel, Dickichte, Hecken)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (150,'5.3.0','Naturferne Pflanzung',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (151,'5.3.0.1','Naturferne Pflanzung mit sommergrünen Arten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (152,'5.3.0.2','Naturferne Pflanzung mit immergrünen Arten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (153,'5.3.1','Besenginster-Gebüsche',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (154,'5.3.2','Trockenwarme Gebüsche auf basenreichem Boden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (155,'5.3.3','Schlehen-Brombeergebüsche',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (156,'5.3.4','Brombeergestrüpp',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (157,'5.3.5','Gebüschreiche Vorwaldgesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (158,'5.3.6','Gebirgsweidenaue',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (159,'5.3.7','Moorweidengebüsche',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (160,'5.3.8','subalpine Karst-Weidengebüsche',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (161,'5.3.9','Grünerlengebüsche',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (162,'5.4','Heiden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (163,'5.4.1','Subatlantische Zwergstrauchheide',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (164,'5.4.2','Kontinentale Zwergstrauchheinde',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (165,'5.4.3','Subalpine Heide auf Kalkboden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (166,'5.4.4','Trockene subalpine Zwergstrauchheide',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (167,'5.4.5','Mesophile subalpine Zwergstrauchheide',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (168,'5.4.6','Arktisch-alpine Zwergstrauchheide',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (169,'6','Wälder',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (170,'6.0','Forstpflanzungen, Einzelbäume',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (171,'6.0.1','Aufforstung mit Laubgehölzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (172,'6.0.2','Aufforstung mit Nadelgehölzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (173,'6.1','Bruch- und Auenwälder',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (174,'6.1.1','Erlen-Bruchwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (175,'6.1.2','Silberweiden-Auenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (176,'6.1.3','Grauerlen-Auenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (177,'6.1.4','Eschen-Auenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (178,'6.2','Buchenwälder',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (179,'6.2.1','Orchideen-Buchenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (180,'6.2.2','Hainsimsen-Buchenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (181,'6.2.3','Waldmeister-Buchenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (182,'6.2.4','Alpenheckenkirschen-Buchenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (183,'6.2.5','Tannen-Buchenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (184,'6.3','Andere Laubwälder',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (185,'6.3.1','Bergahorn-Schluchtwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (186,'6.3.2','Wärmeliebender Linden-Mischwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (187,'6.3.3','Eichen- Hainbuchenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (188,'6.3.4','Flaumeichenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (189,'6.3.5','Hopfenbuchenwald der Alpensüdseite',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (190,'6.3.6','Bodensaurer Eichen-Mischwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (191,'6.3.7','Kastanienwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (192,'6.3.8','Laubwald mit immergrünem Unterholz',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (193,'6.3.9','Robinien-Sekundärwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (194,'6.4','Wärmeliebende Föhrenwälder',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (195,'6.4.1','Pfeifengras-Föhrenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (196,'6.4.2','Subkontinentaler Kalk-Föhrenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (197,'6.4.3','Kontinentaler Steppen-Föhrenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (198,'6.4.4','Mesophiler Föhrenwald auf Silikat',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (199,'6.5','Moorwälder',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (200,'6.5.1','Birken-Moorwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (201,'6.5.2','Torfmoos-Bergföhrenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (202,'6.5.3','Torfmoos-Fichtenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (203,'6.6','Nadelwälder der Hochlagen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (204,'6.6.1','Tannen-Fichtenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (205,'6.6.2','Heidelbeer-Fichtenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (206,'6.6.3','Lärchen-Arvenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (207,'6.6.4','Lärchenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (208,'6.6.5','Bergföhrenwald',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (209,'7','Pioniervegetation oft gestörter Plätze (Ruderalstandorte)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (210,'7.1','Trittrasen und Ruderalfluren',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (211,'7.1.0','Trittflur, Trümmerfeld ohne Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (212,'7.1.1','Feuchte Trittflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (213,'7.1.2','Trockene Trittflur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (214,'7.1.3','Subalpiner und alpiner Trittrasen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (215,'7.1.4','Einjährige Ruderalgesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (216,'7.1.5','Wärmeliebende Ruderalgesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (217,'7.1.6','Mesophile Ruderalgesellschaften',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (218,'7.1.8','Lägergesellschaften der Tieflagen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (219,'7.2','Anthropogene Steinfluren',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (220,'7.2.0','Mauer und Steinpflästerung ohne Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (221,'7.2.1','Ruine und alte Mauer',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (222,'7.2.2','Steinpflästerung',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (223,'8','Pflanzungen, Äcker, Kulturen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (224,'8.1','Baumschulen und Obstgärten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (225,'8.1.1','Baumschule aus Laubgehölzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (226,'8.1.2','Baumschule aus Nadelgehölzen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (227,'8.1.3','Kastanienhain (ohne Unterholz)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (228,'8.1.4','Hochstammobstgarten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (229,'8.1.5','Niederstammobstgarten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (230,'8.1.6','Weinberg',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (231,'8.1.7','Beerenkultur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (232,'8.2','Feldkulturen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (233,'8.2.1','Getreidekultur (Brotgetreide), vorwiegend Winterkultur',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (234,'8.2.1.0','Getreide ohne Ackerbegleitvegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (235,'8.2.1.1','Ackerbegleitvegetation der sauren Böden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (236,'8.2.1.2','Ackerbegleitvegetation kalkreicher Böden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (237,'8.2.2','Mais-, Tabak- und andere Ackerkultur (vorwiegend Sommerkultur)',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (238,'8.2.3','Hackfruchtkultur (Sommerkultur), Gärten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (239,'8.2.3.0','Hackfrucht ohne Begleitflora',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (240,'8.2.3.1','Begleitvegetation der Hackkulturen auf basenarmen Böden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (241,'8.2.3.2','Begleitvegetation der Hackkulturen auf kalkhaltigen Lehmböden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (242,'8.2.3.3','Begleitvegetation der Hackkulturen auf basenarmen lockeren Böden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (243,'8.2.3.4','Begleitvegetation der Hackkulturen auf kalkhaltigen lockeren Böden',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (244,'9','Bauten, Anlagen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (245,'9.1','Lagerplätze, Deponien',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (246,'9.1.1','Misthaufen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (247,'9.1.2','Komposthaufen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (248,'9.1.3','Abfalldeponie im Betrieb',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (249,'9.2','Bauten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (250,'9.2.1','Bewohntes Gebäude',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (251,'9.2.1.1','Keller',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (252,'9.2.1.2','Bewohnte Räumlichkeit, Wohnung',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (253,'9.2.1.3','Estrich, Dachstuhl, Dachstock',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (254,'9.2.1.4','Fassade, Aussenwände',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (255,'9.2.2','Tierstallungen, Gewächshäuser',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (256,'9.2.2.1','Kuh- und Pferdestall',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (257,'9.2.2.2','Schweinestall',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (258,'9.2.2.3','Kaninchen- und Hühnerstall',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (259,'9.2.2.4','Treibhaus',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (260,'9.2.3','Scheune, Schopf',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (261,'9.2.4','Andere Bauten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (262,'9.2.4.1','Turm, Kirchturm',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (263,'9.2.4.2','Wasserspeicher, Schwimmbad',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (264,'9.2.4.3','Fabrik, Halle, Lagerhaus',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (265,'9.2.4.4','Andere Baulichkeiten',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (266,'9.3','Belagsflächen',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (267,'9.3.1','Versiegelte Sportplatz, Parkplatz, etc.',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (268,'9.3.2','Asphalt- oder Betonstrasse',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (269,'9.3.2.1','Strasse',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (270,'9.3.2.2','Autobahn',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (271,'9.3.3','Weg ohne Vegetation',null);
INSERT INTO {habitat} (id,label,name,notes) VALUES (272,'9.4','Bahngleis',null);

