<?php
/**
 * @file habitat.module
 * @author Reto Schneider, 2012
 * @author Ramon Gamma, 2012
 * @copyright 2011-2012 Naturwerk, Brugg
 */

define('ACCESS_CONTENT', 'access habitat');

/**********************************
 *  Hook implementations
 *********************************/

// Load gallery integration
module_load_include('inc', 'habitat', 'habitat.gallery');

/**
 * Implements hook_menu()
 *
 * @return array
 */
function habitat_menu() {
	$items['habitat'] = array(
			'title' => t('Habitats'),
			'description' => t('Show all habitats'),
			'page callback' => 'habitat_show_all',
			'access arguments' => array(
					ACCESS_CONTENT
			),
			'type' => MENU_NORMAL_ITEM,
			'file' => 'habitat.show.inc',
	);

	$items['habitat/%habitat'] = array(
			'title' => 'Show habitat',
			'description' => 'View an existing habitat',
			'page callback' => 'drupal_get_form',
			'access arguments' => array(
					ACCESS_CONTENT
			),
			'page arguments' => array(
					'habitat_show_form',
					1
			),
			'type' => MENU_NORMAL_ITEM,
			'file' => 'habitat.show.inc',
	);
	$items['habitat/datatablejson'] = array(
			'title' => t('Habitat list information in JSON format'),
			'page callback' => 'habitat_list_datatablejson',
			'access arguments' => array(
					ACCESS_CONTENT
			),
			'type' => MENU_CALLBACK,
			'file' => 'habitat.json.inc',
	);
	return $items;
}

/**
 * Return an array with all required information about a habitat.
 * This will be called for menuitems like this: 'habitat/%habitat'
 * @param $arg
 *	This string *should* actually be an integer
 * @return
 * 	Array with all habitat data
 */
function habitat_load($arg) {
	try {
		$result = db_query(
			"SELECT * FROM {habitat} WHERE id = :habitatId",
			array('habitatId' => $arg));
	} catch (Exception $e) {
		drupal_set_message($e->getMessage(), 'error');
		watchdog('habitat', $e->getMessage());
		return array();
	}
	if ($result->rowCount() == 0) {
		drupal_set_title(t("No such habitat available."));
		return array();
	}
	assert($result->rowCount() == 1);
	$habitatdata = (array) $result->fetch();
	return $habitatdata;
}
?>
