<?php
/**
 * @file vote.module
 * @author Emin Khateeb, 2013
 * @author Florian Gyger, 2013
 * @copyright 2011-2013 Naturwerk, Brugg
 */
/**********************************
 *  Hook implementations
 *********************************/

define('VOTE_ACCESS', 'access to voting page');
define('VOTE_WRITE', 'vote for an organism');

/**
 * Implements hook_menu()
 *
 * @return array
 */
function vote_menu() {
	$items['vote'] = array(
			'title' => 'Who knows it?',
			'page callback' => 'vote_show_overview',
			'access arguments' => array(
					VOTE_ACCESS
			),
			'description' => 'Voting page for experts',
			'type' => MENU_NORMAL_ITEM,
			'file' => 'vote.show.inc',
	);
	
	$items['vote/%'] = array(
			'title' => 'Who knows it?',
			'description' => 'Voting page for experts',
			'page callback' => 'vote_show_overview',
			'page arguments' => array(
					1
			),
			'access arguments' => array(
					VOTE_ACCESS
			),
			'file' => 'vote.show.inc',
	);

	return $items;
}

/**
 * Define permissions which can be given to different roles.
 *
 * @note Those permissions are not related to the acl
 */
function vote_permission() {
	return array(
			VOTE_WRITE => array(
					'title' => t('Vote for an organism.'),
			),
			VOTE_ACCESS => array(
					'title' => t('View vote page.'),
			)
	);
}