<?php
/**********************************
 *  Hook implementations
 *********************************/

module_load_include('inc', 'inventory');

/**
 * Implements hook_menu()
 *
 * @return array
 */
function inventory_menu() {
	$items['inventory'] = array(
    'title' => 'Modify Inventory',
    'description' => 'Show all inventories to modify',
    'page callback' => 'inventory_modify',
    'access arguments' => array('access inventories'),
	'file' => 'inventory.edit.list.inc',
	);
	$items['inventory/edit'] = array(
    'title' => 'Modify Inventory',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
	);
	$items['inventory/%/edit'] = array(
    'title' => 'Modify Inventory',
    'description' => 'Modify an existing inventory',
    'page callback' => 'inventory_edit',
    'page arguments' => array(1),
	'access callback' => 'inventory_edit_access',
    'access arguments' => array(1),
    'type' => MENU_NORMAL_ITEM,
	'file' => 'inventory.edit.inc',
	);
	$items['inventory/new'] = array(
    'title' => 'Create Inventory',
    'description' => 'Create a new inventory',
    'page callback' => 'inventory_new',
    'page arguments' => array(1),
    'access arguments' => array('access inventories'),
    'type' => MENU_LOCAL_TASK,
	'file' => 'inventory.new.inc',
	'weight' => 5,
	);
	$items['inventory/organism_autocomplete'] = array(
    'title' => 'Organism Autocomplete',
    'description' => 'JSON Organism Autocomplete',
    'page callback' => 'inventory_organism_autocomplete',
    'access arguments' => array('access inventories'),
    'type' => MENU_CALLBACK,
	'file' => 'inventory.organism_autocomplete.inc',
	);
  
  	return $items;
}

/**
 * Default permission function
 * 
 */
function inventory_permission() {
  return array(
    'access inventories' =>  array(
      'title' => t('can view inventories'),
    ),
    'create inventories' =>  array(
      'title' => t('can create inventories'),
    ),
  );
}

/**
 * Check write acces to inventory
 * 
 * @param unknown_type $inventoryId
 * @return true if access ok, false if not
 */
function inventory_edit_access($inventoryId) {
	$access = user_access('access inventories');
	// check if this user has write access to the inventory
	global $user;
	$adminRecords = db_query('
		SELECT write FROM sgroups_inventory sgi
		LEFT JOIN sgroup_users sgu ON sgu.sgid = sgi.sgid
		WHERE sgi.hiid = :hiid AND sgu.uid = :uid
		ORDER BY write DESC LIMIT 1;', array(':hiid' => $inventoryId, ':uid' => $user->uid)
	);
	$write = $adminRecords->fetch();
	$access = $access && $write->write == 1;
	return $access;
}

/**
 * Check read acces to inventory
 * 
 * @param unknown_type $inventoryId
 * @return true if access ok, false if not
 */
function inventory_access($inventoryId) {
	$access = user_access('access inventories');
	// check if this user has write access to the inventory or the inventory is public
	global $user;
	$adminRecords = db_query('
		SELECT read, shared FROM sgroups_inventory sgi
		LEFT JOIN sgroup_users sgu ON sgu.sgid = sgi.sgid
		LEFT JOIN head_inventory hi ON sgi.hiid = hi.id
		WHERE sgi.hiid = :hiid AND sgu.uid = :uid
		ORDER BY read, shared DESC LIMIT 1;', array(':hiid' => $inventoryId, ':uid' => $user->uid)
	);
	$read = $adminRecords->fetch();
	$access = $access && (($read->read == 1) || ($read->shared == true));
	return $access;
}

?>