<?php
/**********************************
 *  Hook implementations
 *********************************/

/**
 * Implements hook_menu()
 *
 * @return array
 */
function inventory_menu() {
	$items['inventory/new/%'] = array(
    'title' => 'Inventar erstellen',
    'description' => 'Inventar erstellen',
    'page callback' => 'inventory_new',
    'page arguments' => array(1),
    'access arguments' => array('access inventories'),
    'type' => MENU_NORMAL_ITEM,
	'file' => 'inventory.new.inc',
	);
	$items['inventory/edit/%'] = array(
    'title' => 'Inventar bearbeiten',
    'description' => 'Inventar bearbeiten',
    'page callback' => 'inventory_edit',
    'page arguments' => array(1),
    'access arguments' => array('access inventories'),
    'type' => MENU_NORMAL_ITEM,
	'file' => 'inventory.new.inc',
	);
	$items['inventory/%'] = array(
    'title' => 'Inventar Url',
    'description' => 'Swissmon Inventar',
    'page callback' => 'inventory_show',
	'page arguments' => array(1),
    'access arguments' => array('access inventories'),
    'type' => MENU_CALLBACK,
	'file' => 'inventory.pages.inc',
	);
	$items['inventory'] = array(
    'title' => 'Inventare',
    'description' => 'Zeigt alle Inventare',
    'page callback' => 'inventory_overview',
    'access arguments' => array('access inventories'),
    'type' => MENU_NORMAL_ITEM,
	'file' => 'inventory.overview.inc',
	);
	$items['inventory/organism_autocomplete'] = array(
    'title' => 'Organism Autocomplete',
    'description' => 'JSON Organism Autocomplete',
    'page callback' => 'inventory_organism_autocomplete',
    'access arguments' => array('access inventories'),
    'type' => MENU_CALLBACK,
	'file' => 'inventory.organism_autocomplete.inc',
	);
  
  	return $items;
}

function inventory_permission() {
  return array(
    'access inventories' =>  array(
      'title' => t('can view inventories'),
    ),
    'create inventories' =>  array(
      'title' => t('can create inventories'),
    ),
  );
}

?>